cocagne:
  store_id: 31
  api_endpoint: https://admin.cocagne.ch/api/v1/members
  basket_sizes:
    35087: 1 # Grande part
  basket_complements:
    34780: 9 # Oeufs 6 pièces
    34781: 10 # Pain Cora blé 500g
    34782: 12 # Pain Cora épeautre 450g
    34783: 6 # Fromage frais
    34787: 14 # Jus de pomme regarge
  depots:
    34088: 43 # 16 ch. Franconis 1290 Versoix
    34087: 22 # 15 ch. de Roches 1208 Genève

locali:
  store_id: 33
  api_endpoint: https://admin.panier-locali.ch/api/v1/members
  basket_sizes:
    34090: 1 # Panier famille ?
  depots:
    35412: 9 # Vernier (à confirmer)
    35411: 7 # Meyrin Champs Fréchets (à confirmer)
    34101: 4 # Servette
    34099: 1 # Plainpalais
    34100: 3 # Plan les Ouates Sciers (à confirmer)
    34097: 2 # Meyrin Vergers
    34096: 6 # Conches

touviere:
  store_id: 35
  api_endpoint: https://admin.touviere.ch/api/v1/members
  basket_sizes:
    34834: 1 # Panier Couple
    34835: 3 # Panier Famille
  basket_complements:
    34417: 2 # Panier de fruits
    34135: 1 # Boîte d'oeufs BIO 6 pièces
  depots:
    34133: 4 # Servette
    34132: 2 # Chêne-Bourg
    34131: 3 # Jonction
    34129: 1 # Domaine de la Touvière
